:rootdir: ../../..
:github-readme: {rootdir}/README.adoc
:srcdir: {rootdir}/src/
:listing-caption: Listing
:revdate: {project-builddate}
:revnumber: {project-version}

include::{github-readme}[tags=vardef]

:projectpage: https://github.com/{gh-repo-owner}/{gh-repo-name}

include::{github-readme}[tags=header]

== URLs

* link:{homepage}[Project home] (this page)
* link:{projectpage}[GitHub project]
* link:{issues}[Issue tracker]

TIP: Do you want to improve this page? Please git-link:self[edit it on GitHub, edit].

== Description

{project-name} is an extension for AsciidoctorJ that allows to include files using a globbing pattern.

More concretely instead of including different files one by one:

[source, adoc]
.traditional way to include multiple files into a document
----
= My book

\include::content/chapter01.adoc[]

\include::content/chapter02.adoc[]

\include::content/chapter03.adoc[]
----

It is possible to include them all with a single include:

[source, adoc]
.include of files using the dynamic-include processor
----
= My book

\include::dynamic:content/*.adoc[]
----

To control the order of the included files, the approach using `pages.yaml` described in the project link:https://jmini.github.io/path-order/[path-order] can be used.

The processor will take care of the title levels.

Each file can start with a level 2: `== My title`

Meaning that they are valid documents individually.

When the pages are combined using the dynamic-include, the processor will add the corresponding `:leveloffset:` necessary to have a consistent level.
A sub-folder will correspond to a shift of one in the hierarchy, with a special processing of the `index.adoc` page.

This allows to have a tree structure like this:

----
├── chapter-one
│   ├── content-section
│   │   ├── content-1.adoc
│   │   ├── content-2.adoc
│   │   └── index.adoc
│   ├── end-section
│   │   └── index.adoc
│   ├── index.adoc
│   ├── intro.adoc
│   └── pages.yaml
├── chapter-three
│   ├── index.adoc
│   ├── page1.adoc
│   └── page2.adoc
├── chapter-two
│   ├── index.adoc
│   ├── info.adoc
│   ├── pages.yaml
│   ├── section-1.adoc
│   └── section-a.adoc
├── index.adoc
├── index.html
└── pages.yaml
----

== AsciidoctorJ version

This extension is compatible with `org.asciidoctor:asciidoctorj` in range `{asciidoctorj-version}`.

The continuous integration server runs the test suite with different AsciidoctorJ versions within this range.

== Usage examples

The extension is published on maven central and can be directly consumed from maven or gradle.

include::{rootdir}/usage/maven-example/README.adoc[leveloffset=1, tags=maven-integration]

For a complete example, see: git-link:usage/maven-example/pom.xml[pom.xml, branch="master"]

include::{rootdir}/usage/gradle-example/README.adoc[leveloffset=1, tags=gradle-integration]

For a complete example, see: git-link:usage/gradle-example/build.gradle[build.gradle, branch="master"]

== Download

The library is hosted on maven central.

[source, xml, subs="verbatim,attributes"]
.Maven coordinates of the library
----
<dependency>
  <groupId>fr.jmini.asciidoctorj</groupId>
  <artifactId>dynamic-include</artifactId>
  <version>{last-stable-version}</version>
</dependency>
----

== Source Code

As for any grade plugin, the source code of the plugin is available in the git-link:src/[src/] folder.

=== Build

This project is using gradle.

Command to build the sources locally:

----
./gradlew build
----

The AsciidoctorJ version can be controlled with the `asciidoctorjVersion` project property.
The property will influence the strict version in the dependency definition.
This is used to test the extension against a specific AsciidoctorJ version.

Usage example:

----
./gradlew build -PasciidoctorjVersion=2.2.0
----

Command to deploy to your local maven repository:

----
./gradlew publishToMavenLocal
----

Command to build the documentation page:

----
./gradlew asciidoctor
----

The output of this command is an HTML page located at `<git repo root>/build/docs/html5/index.html`.

==== For project maintainers

`signing.gnupg.keyName` and `signing.gnupg.passphrase` are expected to be set in your local `gradle.properties` file to be able to sign.
`sonatypeUser` and `sonatypePassword` are expected to be set in order to be able to publish to a distant repository.

Command to build and publish the result to maven central:

----
./gradlew publishToSonatype
----

Command to upload the documentation page on GitHub pages:

----
./gradlew gitPublishPush
----

Command to perform a release:

----
./gradlew release -Prelease.useAutomaticVersion=true
----

==== Using ssh-agent

Some tasks requires pushing into the distant git repository (release task or updating the `gh-pages` branch).
If they are failing with errors like this:
----
org.eclipse.jgit.api.errors.TransportException: ... Permission denied (publickey).
---- 

Then `ssh-agent` can be used.
----
eval `ssh-agent -s`
ssh-add ~/.ssh/id_rsa
----
(link:https://superuser.com/a/990447/[source] for this approach)


include::{github-readme}[tags=contact-section]

include::{github-readme}[tags=license-section]

